apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
<<<<<<< HEAD
<<<<<<< HEAD
  replicas: 1
=======
  replicas: 3
>>>>>>> fae952b (first commit)
=======
  replicas: 1
>>>>>>> 757c8a5 (updated replicas)
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports: 
        - containerPort: 80
        resources: {}
status: {}
